spring:
  application:
    name: jirkasindelar323

server:
  port: ${PORT:8080}

  web:
    cors:
      allowed-origins: http://localhost:5173,http://localhost
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

logging:
  level:
    com.github.jirkasindelar323: INFO
